spring:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    appId: gcp-application-petryshyn
    gcp:
      sql:
        instance-connection-name: gcp-application-petryshyn:us-central1:database
        database-name: database_for_students
  datasource:
    url: jdbc:mysql://35.223.82.58:3306/database_for_students
    username: root
    password: 20010123
